---
- hosts: all
  become: true
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: ldap.conf
        dest: /etc/ldap/ldap.conf
  
    - name: restart nscd.service
      service:
         name: nscd.service
         state: restarted
         enabled: yes

    - name: restart sudo-ldap.service
      service:
         name: sudo-ldap.service
         state: restarted
         enabled: yes