---
- hosts: all 
  tasks:
  
  - name: agrega key asc
    ansible.builtin.apt_key:
      url: https://baltocdn.com/helm/signing.asc
      state: present
  
  - name: Install apt-transport-https
    apt: 
      name: apt-transport-https
      state: present
    
  - name: Add specified repository into sources list using specified filename
    ansible.builtin.apt_repository:
      repo: deb https://baltocdn.com/helm/stable/debian/ all main
      state: present
      filename: helm-stable-debian.list

  - name: Update apt repo and cache on all Debian/Ubuntu boxes
    apt: 
      update_cache: yes 
      force_apt_get: yes 
      cache_valid_time: 3600
  
  - name: Install helm via repo
    apt: 
      name: helm
      state: present