---
- hosts: all
  tasks:
  gather_facts: yes
  tasks:
  - name: Distribution
    debug: msg="{{ ansible_distribution }}"-"{{ ansible_distribution_major_version }}"-"{{ ansible_distribution_version}}"