---
- hosts: all
  tasks:
  - name: update && upgrade con apt
    apt:
      update_cache: yes

  - name: Update all packages to the latest version
    apt:
      upgrade: dist

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes
