- hosts: all 
  tasks:
  - name: restaurar el archivo interface
    command: mv /etc/network/interfaces.orig /etc/network/interfaces

  - name: Eliminar archivos 
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      -  /etc/systemd/network/10-ens192.network
      -  /usr/local/sbin/kill_llmnr
      -  /etc/systemd/system/kill_llmnr.service

  - name: Executing a command using command module
    shell: "{{ item.com }}"
    register: command_result
    with_items:
      - { com: 'systemctl daemon-reload' }
      - { com: 'systemctl stop kill_llmnr.service' }
      - { com: 'systemctl disable kill_llmnr.service' }

  - name: Ansible shell register result
    debug: msg="{{ command_result }}"
