---
- name: Remove Snapchot
  gather_facts: no
  vars_files:
    - vcenter_vars.yml
  hosts: localhost
  tasks:

    - name: remueve a snapshot
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_ip }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        datacenter: "{{ datacenter_name }}"
        validate_certs: False
        folder: "/{{ datacenter_name }}/vm/"
        name: droopy.d
        state: absent
        snapshot_name: snap1
        description: snap1_description
      delegate_to: localhost